export const LookTags = {
    1: { name: "상황", parent_id: null },
    2: { name: "스타일", parent_id: null },
    3: { name: "계절", parent_id: null },
    4: { name: "퍼스널컬러", parent_id: null },
    5: { name: "바다", parent_id: 1 },
    6: { name: "여행", parent_id: 1 },
    7: { name: "카페", parent_id: 1 },
    8: { name: "데이트", parent_id: 1 },
    9: { name: "소개팅", parent_id: 1 },
    10: { name: "결혼식", parent_id: 1 },
    11: { name: "출근룩", parent_id: 1 },
    12: { name: "데일리", parent_id: 1 },
    13: { name: "졸업식", parent_id: 1 },
    14: { name: "기타", parent_id: 1 },
    15: { name: "미니멀", parent_id: 2 },
    16: { name: "스트릿", parent_id: 2 },
    17: { name: "캐주얼", parent_id: 2 },
    18: { name: "아메카지", parent_id: 2 },
    19: { name: "스포티", parent_id: 2 },
    20: { name: "레트로", parent_id: 2 },
    21: { name: "클래식", parent_id: 2 },
    22: { name: "기타", parent_id: 2 },
    23: { name: "봄", parent_id: 3 },
    24: { name: "여름", parent_id: 3 },
    25: { name: "가을", parent_id: 3 },
    26: { name: "겨울", parent_id: 3 },
    27: { name: "장마", parent_id: 3 },
    28: { name: "눈", parent_id: 3 },
    29: { name: "기타", parent_id: 3 },
    30: { name: "봄 라이트", parent_id: 4 },
    31: { name: "봄 브라이트", parent_id: 4 },
    32: { name: "봄 웜", parent_id: 4 },
    33: { name: "여름 라이트", parent_id: 4 },
    34: { name: "여름 뮤트", parent_id: 4 },
    35: { name: "여름 쿨", parent_id: 4 },
    36: { name: "가을 뮤트", parent_id: 4 },
    37: { name: "가을 딥", parent_id: 4 },
    38: { name: "가을웜", parent_id: 4 },
    39: { name: "겨울 브라이트", parent_id: 4 },
    40: { name: "겨울 딥", parent_id: 4 },
    41: { name: "겨울 쿨", parent_id: 4 },
};
